# Generated by Django 4.1.4 on 2022-12-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
